version: '3'
services:
  gateway:
    container_name: feedback.mor.local
    build: ./nginx
    volumes:
      - ./nginx/nginx-default.development.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      feedback_app:
        condition: service_started
    ports:
      - 8007:8007
    networks:
      - mor_bridge_network
    env_file:
      - .env.local

  feedback_app:
    # container_name: feedback_app
    build: ./app
    ports:
      - "8000"
    env_file:
      - .env.local
    volumes:
      - ./app:/app
    depends_on:
      database:
        condition: service_healthy
    networks:
      - feedback_network
      - mor_bridge_network
    command: ["bash", "/app/deploy/docker-entrypoint.development.sh"]

  database:
    image: postgis/postgis:11-3.3
    shm_size: '1024m'
    ports:
      - "5432"
    env_file:
      - .env.local
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - feedback_network

volumes:
  postgres-data:

networks:
  feedback_network:
    external: true
  mor_bridge_network:
    external: true
