# Generated by Django 3.2.16 on 2023-10-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meldr_nummer', models.CharField(max_length=20)),
                ('feedback_type', models.CharField(choices=[('positief', 'Positief'), ('negatief', 'Negatief')], default='negatief', max_length=10)),
                ('aanmaakdatum', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Feedback',
                'ordering': ('aanmaakdatum',),
            },
        ),
    ]
